addons:
  apt:
    packages:
    - mongodb-org-server
    - oracle-java8-installer
    sources:
    - mongodb-upstart
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
cache:
  directories:
  - $HOME/.m2
env:
- MODULE=oak-jcr
- MODULE=oak-core
- MODULE=oak-it
- MODULE=oak-lucene
- MODULE=oak-run
- MODULE=oak-it-osgi
- MODULE=oak-pojosr
- MODULE=oak-upgrade
install: mvn --batch-mode -DskipTests -Dbaseline.skip=true install -pl :${MODULE} -am -nsu
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: mvn --batch-mode clean verify -Dbaseline.skip=true -PintegrationTesting -Dnsfixtures=DOCUMENT_NS -pl :${MODULE} -nsu
sudo: false
